name: ci
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*"
      - "v[0-9]+.[0-9]+.[0-9]"
  pull_request:
    branches: ["main"]

  workflow_dispatch:
env:
  THRESHOLD: 80.0 # test >80%
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "~1.22.2"
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      - name: Go Vet
        run: go vet ./...

  govulncheck:
    runs-on: ubuntu-22.04
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "~1.22.3"
          check-latest: true

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Prepare dependencies
        run: go mod download

      - name: Test
        run: make coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.txt

  coverage:
    runs-on: ubuntu-latest
    needs: test
    name: Coverage
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Check coverage
        run: |
          total_coverage=$(grep total coverage/coverage.txt | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $total_coverage%"
          threshold=${{ env.THRESHOLD }}
          if (( $(echo "$total_coverage < $threshold" | bc -l) )); then
            echo "Coverage ($total_coverage%) is below threshold ($threshold%)"
            exit 1
          fi
        shell: bash

  build:
    runs-on: ubuntu-22.04
    needs: [lint, test, govulncheck, coverage]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: lafetz/ci-demo:${{  github.ref_name }}
